### ISSUE TITLE
Add this library in the "official" documentation

### ISSUE THREAD

**Issue by gulien** [ChangemakerStudios/GotenbergSharpApiClient#13]
Hello 

Thank you for making this library 👍I just saw your post on reddit and I was wondering if I could add it in the documentation of Gotenberg https://thecodingmachine.github.io/gotenberg/#clients.community_clients?

**Comment by chrismo111** [comment]
Hi Gulien, yes please do.  There's still a few kinks to iron out but HTML to PDF conversion and merging work fine as does Url to pdf.  Office merges work but the builder needs improvement.   Please feel free to list it.  I should have the remaining issues resolved in a week or two.  Thanks for making a great API.

**Comment by gulien** [comment]
Aaand done: https://thecodingmachine.github.io/gotenberg/#clients.community_clients 😄
