### ISSUE TITLE
Gotenberg 6.1.0

### ISSUE THREAD

**Issue by gulien** [ChangemakerStudios/GotenbergSharpApiClient#14]
Hello :)

FYI, I've just released Gotenberg [6.1.0](https://github.com/thecodingmachine/gotenberg/releases/tag/6.1.0) 🎉 

Here is an example with the new features implemented in the go client: https://github.com/thecodingmachine/gotenberg-go-client/releases/tag/v7.0.0

**Comment by chrismo111** [comment]
> Hello :)
> 
> FYI, I've just released Gotenberg [6.1.0](https://github.com/thecodingmachine/gotenberg/releases/tag/6.1.0) 🎉
> 
> Here is an example with the new features implemented in the go client: https://github.com/thecodingmachine/gotenberg-go-client/releases/tag/v7.0.0

Hi Gulien, I just put a new version into the dev branch and plan to merge into master within a week or so when I'll release an updated nuget package for the v1.0 release.  Re: v 6.2.0, I've added all the new features except NewDocumentFromPath.
