### ISSUE TITLE
Compatibility with netcoreapp2.2

### ISSUE THREAD

**Issue by PeterKneale** [ChangemakerStudios/GotenbergSharpApiClient#16]
Should it be possible to reference this from a `netcoreapp2.2` project? 

`Gotenberg.Sharp.Api.Client.csproj` references `Microsoft.Extensions.Http v3.0.0` which appears to prevent this situation
 
* Gotenberg.Sharp.Api.Client.csproj
```xml
...
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.0.0" />
...
```
The change from v2.2.0 to v3.0.0 took place [here](https://github.com/ChangemakerStudios/GotenbergSharpApiClient/commit/0f2808a93ba1d6adf9eda6fba08de7c32552bc35#diff-cb20ef43443f872cc84d1ce27608855fR20)

**Comment by chrismo111** [comment]
Just pushed a new version after having removed Microsoft.Extensions.Http.  It wasn't used anyway.
