### ISSUE TITLE
Gotenberg 6.2.0

### ISSUE THREAD

**Issue by gulien** [ChangemakerStudios/GotenbergSharpApiClient#17]
Hello 😄 

FYI, I've just released Gotenberg [6.2.0](https://github.com/thecodingmachine/gotenberg/releases/tag/6.2.0) 🎉 

The API now accepts a new form field `scale` for HTML, URL and Markdown conversions (see https://thecodingmachine.github.io/gotenberg/#html.paper_size_margins_orientation_scaling).

Thank you again for this client 👍 

Related #14

**Comment by kbdavis07** [comment]
I don't see scale as an option in the DocumentDimensions class?

Is this going to be updated in the C# Client?

**Comment by chrismo111** [comment]
Will update soon.

**Comment by chrismo111** [comment]
> I don't see scale as an option in the DocumentDimensions class?
> 
> Is this going to be updated in the C# Client?

OK.. its in the latest nuget. Updated the sample code to show how it's used. Also added support for the page range feature. For now you call that on the builder via   .ConfigureRequest.PageRanges("2-4").Document

**Comment by chrismo111** [comment]
This is all done and I added a "SetPaperHeight" method for setting the width and height in one call.
