### ISSUE TITLE
Parsing error on demensions parse float issue

### ISSUE THREAD

**Issue by schadowfax** [ChangemakerStudios/GotenbergSharpApiClient#19]
I started using the example defined in the getting started and had instantly this error:

{"level":"error","msg":"strconv.ParseFloat: parsing \"0,5\": invalid syntax","op":"xhttp.htmlHandler: xhttp.chromePrinterOptions: resource.MarginArgs: resource.Resource.Float64Arg: xassert.Float64","time":"2020-03-04T09:27:32Z","trace":"RP4I2w1Xa684qWtwV7zeeRktGsi3j9I8"}

**Comment by chrismo111** [comment]
HI, I just tested the code sample in two environments and could not reproduce the error.  Pdfs were successfully created with no errors in the logs, even when I set margin left and right to zero.

The latest Gotenberg.Sharp nuget is 0.9.37.

Gotenberg images used in my tests:
On Windows in a linux container: v 6.2.0 (currently latest);
On OsX using image version v 6.1.0 

If you're using v 5.x, please try again with the latest image.

**Comment by chrismo111** [comment]
@schadowfax -- it turns out this was a globalization issue which is why I was not able to reproduce the problem.  I just merged a PR with the fix into the dev branch.  Values are now converted to string using w/ an instance of CultureInfo.GetCultureInfo("en-US").
