### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by runes83** [ChangemakerStudios/GotenbergSharpApiClient#21]
It looks like the client returns the result on error without any hints that is response is not 200 OK. Should it not throw an exception at least?

**Comment by chrismo111** [comment]
Good point.  I'll fix that soon, once the new version I'm working on is ready (branch VNext). Thanks!!

**Comment by chrismo111** [comment]
> It looks like the client returns the result on error without any hints that is response is not 200 OK. Should it not throw an exception at least?

Hi, I just merged the fix into the dev branch.  I plan on merging to master a release a new nuget within a week or so.
