### ISSUE TITLE
New version of Gotenberg 🚀 

### ISSUE THREAD

**Issue by gulien** [ChangemakerStudios/GotenbergSharpApiClient#29]
Hello here 👋 

I've just released version `7.0.0` of Gotenberg 🎉 

A lot of minor changes, the best if you wish to update your  C# client is to head to the [new documentation](https://gotenberg.dev).

Also, I've added your repository to the [awesome list](https://github.com/gotenberg/awesome-gotenberg) 😄  currently, I've marked it as only compatible with Gotenberg **6.x**, but do not hesitate to open a PR when your client is compatible with version 7 👍 

PS: if you have any questions, please ask them!

**Comment by roddone** [comment]
Hi, 

Apparently there is a branch "feature/v7" for gotenberg 7 support. do you have any idea when it would be released ?

**Comment by Cipery** [comment]
+1 on support of v7, please <3

**Comment by chrismo111** [comment]
FYI, the V7 branch works against v7.  That said, If you use the linqpad scripts to test it out you’ll need to reference the client locally since they all still rely on the old package.  I plan on making a release in a few weeks after some refactoring. More importantly, I need to make sure I’ve added all the new features and removed stale ones. I don’t foresee any breaking changes.

**Comment by gulien** [comment]
Hello @chrismo111 👋 I've added your C# client to the [documentation](https://gotenberg.dev/docs/clients). I hope it brings more folks to your repository 😄

**Comment by clarity99** [comment]
hi, just wondering how's it going with the v7 release? In september it was mentioned it would take few weeks?

**Comment by chrismo111** [comment]
Haven’t had the time to work on it. I’ll try to catch up soon.

**Comment by bend** [comment]
Hi, 

Is it possible to push a pre-release package for the v7 feature branch ? 
Do you know when it will be available as a release ? 

Thank you

**Comment by chrismo111** [comment]
@bend, alpha is now live on nuget.org. V7 branch is now merged into dev. Still want to make some minor tweaks. Will merge into master after that.

**Comment by borisr84** [comment]
Hi, I am using the new Gotenberg version and the .NET pre release version. 
Wanted to ask if and when the release version will be released. 

Thank you!

**Comment by Jaben** [comment]
v2.0 has been released!

**Comment by gulien** [comment]
I've updated the documentation, thanks 👍
