### ISSUE TITLE
No emulatedMediaType option for v7

### ISSUE THREAD

**Issue by jacokok** [ChangemakerStudios/GotenbergSharpApiClient#30]
There is currently no emulatedMediaType=screen option.

This option renders page exactly what it looks like on web and not in print mode.

I will be happy to contribute to v7 branch if you need any help.

**Comment by jacokok** [comment]
Seems like we can do something like the below for now, but it will be nice if there is build in option.

```csharp
.CustomHttpHeaders(c => c.AddItem("emulatedMediaType", "screen"));
```

**Comment by chrismo111** [comment]
See the end of this commit message: https://github.com/ChangemakerStudios/GotenbergSharpApiClient/commit/d5b66f5e3cf65d7dc09d6699414ede98785dc86b

**Comment by chrismo111** [comment]
@jacokok, it's in there now. Exposed through the builder as EmulateAsScreen.  Since it emulates print by default.. didn't bother adding a method for that.  Use the UrlConvert linqpad script to see it in action.  Closing this.  Still some more to do before making a new release but its close.

**Comment by jacokok** [comment]
Perfect thank you!
