### ISSUE TITLE
Container returns "Not Found" for all endpoints

### ISSUE THREAD

**Issue by paulomac1000** [ChangemakerStudios/GotenbergSharpApiClient#31]
I get 404 response for each gotenberg container endpoint. I tried every way to create it, each one returns the same - the string "Not Found" along with the HTTP 404 code. In the logs I get this:
![image](https://user-images.githubusercontent.com/9095484/149644392-45cde7a4-c961-453c-bb26-693c3aeacf00.png)

I tried to use images, but neither works:
-  thecodingmachine/gotenberg:latest
-  thecodingmachine/gotenberg:7
-  gotenberg/gotenberg:gotenberg:latest
-  thecodingmachine/gotenberg:7

Using from within code also doesn't work. I have no ideas what else to do. I am asking for tips and correction of the log, because the present say nothing.

**Comment by chrismo111** [comment]
This could be a couple of things:

- If you are using the nuget package, it targets version 6 of the gotenberg image and will not work with latest.   V7 has significant breaking changes. 
- We do have a v7 branch that should work but it doesn’t support all the features yet.  If you are using that branch and trying to use the linqpad scripts, remove the nuget from them and reference the dlls locally. 
-  If you’ve already tried that then that must mean the latest version of the image has more breaking changes.

**Comment by paulomac1000** [comment]
@chrismo111 
Since there is no nuget package compatible with the latest version 7 yet, do you recommend using the docker image in version 6?

**Comment by chrismo111** [comment]
@paulomac1000, I'd use the most recent v6 image,6.4.4.  We're going to support V7 in the near future.  

docker pull thecodingmachine/gotenberg:6.4.4
