### ISSUE TITLE
Can we post byte array office file to get byte array pdf? 

### ISSUE THREAD

**Issue by muhyilmaz** [ChangemakerStudios/GotenbergSharpApiClient#35]
I want to post my byte array office file/files to client and get byte array pdf. How can I do this?

I asked my question here but I couldn't do it.
Here:
https://github.com/gotenberg/gotenberg/discussions/481#discussioncomment-3366438

**Comment by Jaben** [comment]
Try with the latest release: v2.0.1.

**Comment by Jaben** [comment]
Closing for now -- reopen if the problem persists.
