### ISSUE TITLE
Breaking change in .NET 6 causes this client to throw exception because of  Globalization issues

### ISSUE THREAD

**Issue by Deltids** [ChangemakerStudios/GotenbergSharpApiClient#36]
In .Net 6 it is know thrown exception if invariant culture is enabled, but the app is creating a specific culture. 

E.g. see this:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/6.0/culture-creation-invariant-mode

Below is a line from your code where a specific culture info is used. Maybe just set it to Cultureinfo.InvariantCulture?

https://github.com/ChangemakerStudios/GotenbergSharpApiClient/blob/f8ec91768e52152f36cbe8040dbec51f540fea66/lib/Domain/Requests/Facets/Dimensions.cs#L184

**Comment by Jaben** [comment]
Thanks for the heads up.

The reason for this change was: https://github.com/ChangemakerStudios/GotenbergSharpApiClient/issues/25

Switching it to InvariantCulture should still work -- but I'd need someone to test internationally (e.g. @WitchHunter0815).

**Comment by Jaben** [comment]
Released in v2.0
