### ISSUE TITLE
Support for trace

### ISSUE THREAD

**Issue by anielsen** [ChangemakerStudios/GotenbergSharpApiClient#38]
Please add support for the trace feature in Gotenberg.

https://gotenberg.dev/docs/modules/api#trace-all-routes

The purpose of sending a Trace header is to make it easier to find out which client request caused which log entry on the server (gotenberg) side.

**Comment by Jaben** [comment]
This feature is in 2.1.1 (just released).

Configure it in the "ConfigureRequest" call:

![image](https://user-images.githubusercontent.com/448726/193432090-5548ef02-47df-4e98-9961-6bea275b30a8.png)

**Comment by anielsen** [comment]
Thank you Jaben. I am now using this feature  :-)
