### ISSUE TITLE
how to set title to pdf?

### ISSUE THREAD

**Issue by VitaliKhileuski** [ChangemakerStudios/GotenbergSharpApiClient#42]

**Comment by Jaben** [comment]
Try and set the title in the HTML file: https://www.w3schools.com/tags/tag_title.asp

**Comment by Jaben** [comment]
![image](https://github.com/ChangemakerStudios/GotenbergSharpApiClient/assets/448726/464ac4a9-aed5-4076-98c5-2a45e93afc61)
